// Code generated by wit-bindgen-go. DO NOT EDIT.

package ipnamelookup

import (
	"github.com/fermyon/spin-go-sdk/v2/internal/wasi/sockets/v0.2.0/network"
	"github.com/ydnar/wasm-tools-go/cm"
	"unsafe"
)

// OptionIPAddressShape is used for storage in variant or result types.
type OptionIPAddressShape struct {
	shape [unsafe.Sizeof(cm.Option[network.IPAddress]{})]byte
}
