spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go that performs outbound HTTP requests."
name = "http-outbound-example"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "hello/main.wasm"

allowed_outbound_hosts = [
  "https://google.com",
  "https://random-data-api.fermyon.app:443",
  "https://postman-echo.com:443",
]

[component.hello.build]
workdir = "hello"
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/fermyon/spin-go-sdk/v2)/wit --wit-world http-trigger -gc=leaking -no-debug -o main.wasm main.go"



