name: Run Integration tests
on:
  push:
    branches:
      - wasip2-http

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Integration Tests
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: .
          args: test-incoming-http --source .
